# Cloudflare Worker configuration for HelloJack contact form handler
name = "hellojack-form-handler"
main = "worker.js"
compatibility_date = "2024-01-01"

[observability.logs]
enabled = true

# Environment variables (secrets will be added via CLI)
[vars]
# Add any non-secret environment variables here

# Production environment
[env.production]
name = "hellojack-form-handler"
routes = [
  { pattern = "form-handler.hellojack.ai/submit", zone_name = "hellojack.ai" }
]

# Development environment  
[env.development]
name = "hellojack-form-handler-dev"

# Required secrets (set these via: wrangler secret put VARIABLE_NAME)
# RESEND_API_KEY - Your Resend API key
# NOTIFICATION_EMAIL - Email address to receive notifications